name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. Descargar el código
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # 2. Dejar que Azure compile y suba todo automáticamente de forma nativa
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_GLACIER_0A05F1710 }}
          action: "upload"
          ###### CONFIGURACIÓN NATIVA PARA BLAZOR ######
          app_location: "./TommyLogistic.Web" # Carpeta de tu proyecto cliente
          api_location: "" # Vacío porque tu API está en otro App Service
          output_location: "wwwroot" # El motor de Azure sabe que aquí se genera Blazor
          skip_app_build: false # Forzamos a que Azure haga el build seguro
          ##############################################

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
